# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutMe.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QGraphicsPixmapItem, QGraphicsScene


class Ui_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)

        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(100, 20, 192, 192))
        self.graphicsView.setObjectName("graphicsView")

        frame = QImage("./file/cat.jpg")
        pix = QPixmap.fromImage(frame).scaled(190, 190)
        print(f"pix:{pix}")
        item = QGraphicsPixmapItem(pix)
        scene = QGraphicsScene()
        scene.addItem(item)
        self.graphicsView.setScene(scene)

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 220, 130, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 220, 130, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton.clicked.connect(self.msggivinglikes)
        self.pushButton_2.clicked.connect(self.msglikeme)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关于我"))
        self.pushButton.setText(_translate("Dialog", "为元宝点赞"))
        self.pushButton_2.setText(_translate("Dialog", "我喜欢元宝"))

    def msggivinglikes(self):
        QtWidgets.QMessageBox.about(self, "元宝尧尧提示", "今天也要开开心心，早点休息哦!")

    def msglikeme(self):
        QtWidgets.QMessageBox.about(self, "元宝尧尧提示", "我也喜欢你!              ")
