# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editNames.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(524, 313)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 66, 350, 20))
        self.label_2.setObjectName("label_2")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setGeometry(QtCore.QRect(430, 30, 41, 31))
        self.toolButton.setObjectName("toolButton")

        # 选择old_names文件夹
        self.toolButton.clicked.connect(self.getold_namesfolderpath)

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 190, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        # 根据excel内容批量修改文件名
        self.pushButton_2.clicked.connect(self.rewrite_new_names)

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 600, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 400, 21))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 6, 350, 20))
        self.label.setObjectName("label")
        self.toolButton_2 = QtWidgets.QToolButton(Dialog)
        self.toolButton_2.setGeometry(QtCore.QRect(430, 90, 41, 31))
        self.toolButton_2.setObjectName("toolButton_2")

        # 选择excel生成文件夹
        self.toolButton_2.clicked.connect(self.getnew_namesfolderpath)

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 120, 121, 31))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.write_in_excel)

        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 90, 411, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 411, 31))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "批量修改文件夹中文件名称"))
        self.label_2.setText(_translate("Dialog", "第二步：选择生成的excel所在位置"))
        self.toolButton.setText(_translate("Dialog", "..."))
        self.pushButton_2.setText(_translate("Dialog", "点击确认修改"))
        self.label_3.setText(_translate("Dialog", "第三步：在excel中添加修改信息(注意是在B列一一对应关系，不能为空)"))
        self.label_4.setText(_translate("Dialog", "第四步：修改完成后点击按钮一键修改文件名"))
        self.label.setText(_translate("Dialog", "第一步：选择批量改名文件所在文件夹"))
        self.toolButton_2.setText(_translate("Dialog", "..."))
        self.pushButton.setText(_translate("Dialog", "点击生成excel"))

    def getold_namesfolderpath(self, filepath):
        self.path_old_names = QtWidgets.QFileDialog.getExistingDirectory(None, "选取文件夹", "C:/")
        self.textBrowser.setText(self.path_old_names)
        file_list_names = self.read_old_names()
        return self.path_old_names

    def getnew_namesfolderpath(self, filepath):
        self.path_excel = QtWidgets.QFileDialog.getExistingDirectory(None, "选取文件夹", "C:/")
        print(f"{self.path_excel}")
        self.textBrowser_2.setText(self.path_excel)
        return self.path_excel

    # 读取文件夹中老名字
    def read_old_names(self):
        os.chdir(rf"{self.path_old_names}")
        # 读取老名字
        self.filelist = os.listdir(self.path_old_names)
        return self.filelist

    # 写入excel
    def write_in_excel(self):
        df = pd.DataFrame({'Data': self.filelist})
        writer = pd.ExcelWriter(rf"{self.path_excel}\editNames.xlsx", engine='openpyxl')

        df.to_excel(writer, sheet_name="Data", startcol=0, index=False)
        # save的话会导致excel报错
        # writer.save()
        writer.close()

    # 读取excel内容
    def read_old_excel_content(self):
        content = pd.read_excel(rf"{self.path_excel}\editNames.xlsx", engine="openpyxl", usecols=[0], names=None)
        content_li = content.values.tolist()
        result = []
        for s_li in content_li:
            result.append(s_li[0])
        print(f"最终result为：{result}")
        return result

    def read_new_excel_content(self):
        print(f"path_excel:{self.path_excel}")
        content = pd.read_excel(rf"{self.path_excel}\editNames.xlsx", engine="openpyxl", usecols=[1], names=None)
        content_li = content.values.tolist()
        result = []
        for s_li in content_li:
            result.append(s_li[0])
        print(f"最终result为：{result}")
        return result

    # 修改新名字
    def rewrite_new_names(self):
        os.chdir(self.path_old_names)
        newFilelistName = self.read_new_excel_content()
        oldFilelistName = self.read_old_excel_content()
        index = 0
        print(f"old_name:{oldFilelistName}")
        print(f"new_names:{newFilelistName}")
        for new_name in newFilelistName:
            os.rename(oldFilelistName[index], new_name)
            index += 1
