# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extractExcel.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

import pandas as pd
import xlsxwriter
from PyQt5 import QtCore, QtGui, QtWidgets
from openpyxl import load_workbook
from openpyxl_image_loader import SheetImageLoader


class Ui_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(581, 374)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 581, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(0, 20, 371, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(0, 240, 231, 31))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.mergeallsheetspics)

        self.toolButton = QtWidgets.QToolButton(self.tab)
        self.toolButton.setGeometry(QtCore.QRect(370, 20, 41, 31))
        self.toolButton.setObjectName("toolButton")

        self.toolButton.clicked.connect(self.getexcelpath1)

        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 381, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 190, 451, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_5.setGeometry(QtCore.QRect(0, 210, 371, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_6.setGeometry(QtCore.QRect(0, 160, 371, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(0, 140, 451, 20))
        self.label_12.setObjectName("label_12")
        self.toolButton_6 = QtWidgets.QToolButton(self.tab)
        self.toolButton_6.setGeometry(QtCore.QRect(370, 160, 41, 31))
        self.toolButton_6.setObjectName("toolButton_6")

        self.toolButton_6.clicked.connect(self.getnewpathexcel1)

        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(0, 50, 451, 20))
        self.label_16.setObjectName("label_16")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_11.setGeometry(QtCore.QRect(0, 70, 371, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.toolButton_9 = QtWidgets.QToolButton(self.tab)
        self.toolButton_9.setGeometry(QtCore.QRect(370, 70, 41, 31))
        self.toolButton_9.setObjectName("toolButton_9")

        self.toolButton_9.clicked.connect(self.getpicpath1)

        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(0, 100, 451, 20))
        self.label_19.setObjectName("label_19")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(90, 120, 31, 21))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(0, 120, 31, 21))
        self.label_10.setObjectName("label_10")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_3.setGeometry(QtCore.QRect(40, 120, 42, 22))
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setProperty("value", 100)
        self.spinBox_3.setObjectName("spinBox_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 120, 31, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_2.setGeometry(QtCore.QRect(370, 20, 41, 31))
        self.toolButton_2.setObjectName("toolButton_2")

        self.toolButton_2.clicked.connect(self.getexcelpath2)

        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 20, 371, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setGeometry(QtCore.QRect(40, 170, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_2.setGeometry(QtCore.QRect(130, 170, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 290, 211, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_2.clicked.connect(self.mergetspecifiedsheetspics)

        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 481, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 150, 491, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 31, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(90, 170, 31, 21))
        self.label_6.setObjectName("label_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_7.setGeometry(QtCore.QRect(0, 210, 371, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(0, 240, 461, 20))
        self.label_8.setObjectName("label_8")
        self.toolButton_7 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_7.setGeometry(QtCore.QRect(370, 210, 41, 31))
        self.toolButton_7.setObjectName("toolButton_7")

        self.toolButton_7.clicked.connect(self.getnewpathexcel2)

        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_8.setGeometry(QtCore.QRect(0, 260, 371, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(0, 190, 471, 20))
        self.label_13.setObjectName("label_13")
        self.textEdit_12 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_12.setGeometry(QtCore.QRect(0, 70, 371, 31))
        self.textEdit_12.setObjectName("textEdit_12")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(0, 50, 451, 20))
        self.label_17.setObjectName("label_17")
        self.toolButton_10 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_10.setGeometry(QtCore.QRect(370, 70, 41, 31))
        self.toolButton_10.setObjectName("toolButton_10")

        self.toolButton_10.clicked.connect(self.getpicpath2)

        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(0, 100, 451, 20))
        self.label_20.setObjectName("label_20")

        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(90, 120, 31, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(0, 120, 31, 21))
        self.label_22.setObjectName("label_22")
        self.spinBox_6 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_6.setGeometry(QtCore.QRect(40, 120, 42, 22))
        self.spinBox_6.setMaximum(1000)
        self.spinBox_6.setProperty("value", 100)
        self.spinBox_6.setObjectName("spinBox_6")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(110, 120, 31, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 20, 371, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 481, 20))
        self.label_9.setObjectName("label_9")
        self.toolButton_3 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_3.setGeometry(QtCore.QRect(370, 20, 41, 31))
        self.toolButton_3.setObjectName("toolButton_3")

        self.toolButton_3.clicked.connect(self.getexcelpath3)

        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(0, 140, 481, 20))
        self.label_11.setObjectName("label_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 290, 231, 31))
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.mergetspecifiednamessheets)

        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_4.setGeometry(QtCore.QRect(0, 160, 371, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.toolButton_4 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_4.setGeometry(QtCore.QRect(370, 160, 41, 31))
        self.toolButton_4.setObjectName("toolButton_4")

        self.toolButton_4.clicked.connect(self.readnames)

        self.toolButton_8 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_8.setGeometry(QtCore.QRect(370, 210, 41, 31))
        self.toolButton_8.setObjectName("toolButton_8")

        self.toolButton_8.clicked.connect(self.getnewpathexcel3)

        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(0, 240, 461, 20))
        self.label_14.setObjectName("label_14")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_9.setGeometry(QtCore.QRect(0, 210, 371, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_10.setGeometry(QtCore.QRect(0, 260, 371, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(0, 190, 471, 20))
        self.label_15.setObjectName("label_15")
        self.textEdit_13 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_13.setGeometry(QtCore.QRect(0, 70, 371, 31))
        self.textEdit_13.setObjectName("textEdit_13")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(0, 50, 451, 20))
        self.label_18.setObjectName("label_18")
        self.toolButton_11 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_11.setGeometry(QtCore.QRect(370, 70, 41, 31))
        self.toolButton_11.setObjectName("toolButton_11")

        self.toolButton_11.clicked.connect(self.getpicpath3)

        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(0, 100, 451, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(0, 120, 31, 21))
        self.label_24.setObjectName("label_24")
        self.spinBox_7 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_7.setGeometry(QtCore.QRect(40, 120, 42, 22))
        self.spinBox_7.setMaximum(1000)
        self.spinBox_7.setProperty("value", 100)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(90, 120, 31, 21))
        self.label_25.setObjectName("label_25")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 120, 31, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "提取图片并合并到新excel文件中"))
        self.tabWidget.setToolTip(_translate("Dialog", "<html><head/><body><p></p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("Dialog", "<html><head/><body><p></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "点击合并excel所有sheets中图片"))
        self.toolButton.setText(_translate("Dialog", "选择"))
        self.label.setText(_translate("Dialog", "第一步：选择excel所在位置"))
        self.label_2.setText(_translate("Dialog", "第五步：填写新生成excel名字(格式为aaa)并点击生成"))
        self.label_12.setText(_translate("Dialog", "第四步：选择新生成excel所在位置"))
        self.toolButton_6.setText(_translate("Dialog", "选择"))
        self.label_16.setText(_translate("Dialog", "第二步：选择提取图片暂存文件夹，建议为空文件夹"))
        self.toolButton_9.setText(_translate("Dialog", "选择"))
        self.label_19.setText(_translate("Dialog", "第三步：选择excel中最大行列范围，请保证能包含到图片"))
        self.label_7.setText(_translate("Dialog", "列："))
        self.label_10.setText(_translate("Dialog", "行："))
        self.lineEdit_2.setText(_translate("Dialog", "Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "合并所有sheets表中图片"))
        self.toolButton_2.setText(_translate("Dialog", "选择"))
        self.pushButton_2.setText(_translate("Dialog", "点击合并excel中指定sheets图片"))
        self.label_3.setText(_translate("Dialog", "第一步：选择excel所在位置"))
        self.label_4.setText(_translate("Dialog", "第四步：选择sheet开始位置与结束位置(0代表sheet1)"))
        self.label_5.setText(_translate("Dialog", "开始："))
        self.label_6.setText(_translate("Dialog", "结束："))
        self.label_8.setText(_translate("Dialog", "第六步：填写新生成excel名字(格式为aaa)并点击生成"))
        self.toolButton_7.setText(_translate("Dialog", "选择"))
        self.label_13.setText(_translate("Dialog", "第五步：选择新生成excel所在位置"))
        self.label_17.setText(_translate("Dialog", "第二步：选择提取图片暂存文件夹，建议为空文件夹"))
        self.toolButton_10.setText(_translate("Dialog", "选择"))
        self.label_20.setText(_translate("Dialog", "第三步：选择excel中最大行列范围，请保证能包含到图片"))
        self.label_21.setText(_translate("Dialog", "列："))
        self.label_22.setText(_translate("Dialog", "行："))
        self.lineEdit.setText(_translate("Dialog", "Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "合并连续sheets表中图片"))
        self.label_9.setText(_translate("Dialog", "第一步：选择excel所在位置"))
        self.toolButton_3.setText(_translate("Dialog", "选择"))
        self.label_11.setText(_translate("Dialog", "第四步：填写sheet表具体名称（用数字\",\"隔开），填写完成后点击确定"))
        self.pushButton_3.setText(_translate("Dialog", "点击合并excel中具体名称sheets中图片"))
        self.toolButton_4.setText(_translate("Dialog", "确定"))
        self.toolButton_8.setText(_translate("Dialog", "选择"))
        self.label_14.setText(_translate("Dialog", "第六步：填写新生成excel名字(格式为aaa)并点击生成"))
        self.label_15.setText(_translate("Dialog", "第五步：选择新生成excel所在位置"))
        self.label_18.setText(_translate("Dialog", "第二步：选择提取图片暂存文件夹，建议为空文件夹"))
        self.toolButton_11.setText(_translate("Dialog", "选择"))
        self.label_23.setText(_translate("Dialog", "第三步：选择excel中最大行列范围，请保证能包含到图片"))
        self.label_24.setText(_translate("Dialog", "行："))
        self.label_25.setText(_translate("Dialog", "列："))
        self.lineEdit_3.setText(_translate("Dialog", "Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "合并指定名称sheets表中图片"))

    # 合并所有sheets中图片
    def getexcelpath1(self):
        self.pathexcel1, filetype = QtWidgets.QFileDialog.getOpenFileName(self, "选取文件", "C:/", "xlsx Files (*.xlsx)")
        self.textEdit.setText(self.pathexcel1)

    def getpicpath1(self):
        self.pathpic1 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取暂存文件夹", "C:/")
        self.textEdit_11.setText(self.pathpic1)

    def getnewpathexcel1(self):
        self.newpathexcel1 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取新excel文件夹", "C:/")
        self.textEdit_6.setText(self.newpathexcel1)

    def mergeallsheetspics(self):
        newnameexcel1 = self.textEdit_5.toPlainText()
        self.extractpics(self.pathpic1, self.pathexcel1, 1)
        self.writepicsintoexcel(newnameexcel1, self.newpathexcel1, self.pathpic1)

    # 合并连续sheets中图片
    def getexcelpath2(self):
        self.pathexcel2, filetype = QtWidgets.QFileDialog.getOpenFileName(self, "选取文件", "C:/", "xlsx Files (*.xlsx)")
        self.textEdit_2.setText(self.pathexcel2)

    def getpicpath2(self):
        self.pathpic2 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取暂存文件夹", "C:/")
        self.textEdit_12.setText(self.pathpic2)

    def getnewpathexcel2(self):
        self.newpathexcel2 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取新excel文件夹", "C:/")
        self.textEdit_7.setText(self.newpathexcel2)

    def mergetspecifiedsheetspics(self):
        newnameexcel2 = self.textEdit_8.toPlainText()
        self.extractpics(self.pathpic2, self.pathexcel2, 2)
        self.writepicsintoexcel(newnameexcel2, self.newpathexcel2, self.pathpic2)

    # 合并具体名称sheets中图片
    def getexcelpath3(self):
        self.pathexcel3, filetype = QtWidgets.QFileDialog.getOpenFileName(self, "选取文件", "C:/", "xlsx Files (*.xlsx)")
        self.textEdit_3.setText(self.pathexcel3)

    def getpicpath3(self):
        self.pathpic3 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取暂存文件夹", "C:/")
        self.textEdit_13.setText(self.pathpic3)

    def readnames(self):
        namesheets = self.textEdit_4.toPlainText()
        self.arrnamessheets = namesheets.split(',')

    def getnewpathexcel3(self):
        self.newpathexcel3 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取新excel文件夹", "C:/")
        self.textEdit_9.setText(self.newpathexcel3)

    def mergetspecifiednamessheets(self):
        newnameexcel3 = self.textEdit_10.toPlainText()
        self.extractpics(self.pathpic3, self.pathexcel3, 3)
        self.writepicsintoexcel(newnameexcel3, self.newpathexcel3, self.pathpic3)

    # 提取excel单元格中图片到指定位置
    def extractpics(self, savedirtemp, pathexcelname, key):
        savedir = savedirtemp + '\\'

        df = pd.read_excel(pathexcelname, sheet_name=None)
        rowvalue = 100
        columvalue = 'Z'
        if key == 1:
            sheetnames = list(df)
            rowvalue = self.spinBox_3.value()
            columvalue = self.lineEdit_2.text()
        if key == 2:
            sheetnames = list(df)[self.spinBox.value():self.spinBox_2.value()]
            rowvalue = self.spinBox_6.value()
            columvalue = self.lineEdit.text()
        if key == 3:
            sheetnames = self.arrnamessheets
            rowvalue = self.spinBox_7.value()
            columvalue = self.lineEdit_3.text()

        print(f"sheetnames:{sheetnames}")
        print(f"rowvalue:{rowvalue}")
        print(f"columnvalue:{columvalue}")
        for sheetname in sheetnames:
            wb = load_workbook(pathexcelname)  # Excel文件名
            ws = wb.get_sheet_by_name(sheetname)
            image_loader = SheetImageLoader(ws)

            for i in range(0, rowvalue):  # 从第2行开始，总行数要+1
                for j in range(ord('A'), ord(columvalue) + 1):
                    try:
                        # 设定名字
                        image = image_loader.get(f'{chr(j)}{i}')
                        image.save(savedir + sheetname + f"{chr(j)}{i}.jpg")

                        # 排除没有图片，或图片超出单元格的情况
                    except ValueError:
                        pass
            image_loader._images.clear()

    # 将图片写入excel
    def writepicsintoexcel(self, newexcelname, newexcelpath, picpath):
        self.filelist = os.listdir(picpath)
        wb = xlsxwriter.Workbook(newexcelpath + '/' + newexcelname + '.xlsx')
        ws = wb.add_worksheet('Sheet1')
        ws.set_column('A:A', 7)
        ws.set_column(1, 2, 50)

        # 指定head
        headings = ['图片']

        # 设置excel风格
        head_format = wb.add_format(
            {'bold': 1, 'fg_color': 'blue', 'align': 'center', 'font_name': u'微软雅黑', 'valign': 'vcenter'})
        ws.write_row('A1', headings, head_format)

        j = 0

        # 将获取到的各种标签信息写入excel
        for k in range(len(self.filelist)):
            # print(f"fileList[i]:{self.filelist[k]}")
            ws.set_row(k + 1 + j * 25, 60)
            ws.insert_image('A' + str(k + 2 + j * 25), f'{picpath}/{self.filelist[k]}',
                            {'x_scale': 0.2, 'y_scale': 0.2})
        j += 1
        wb.close()
