# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

import aboutMe
import editNames
import mergeSheets
import extractExcel


class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        self.child_aboutMe = aboutMe
        self.child_editNames = editNames
        self.child_mergeSheets = mergeSheets
        self.child_extractExcel = extractExcel

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 180, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 295, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuexcel = QtWidgets.QMenu(self.menu)
        self.menuexcel.setObjectName("menuexcel")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actiongong = QtWidgets.QAction(MainWindow)
        self.actiongong.setObjectName("actiongong")
        self.action_sheet = QtWidgets.QAction(MainWindow)
        self.action_sheet.setObjectName("action_sheet")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.actionShowAboutMe = QtWidgets.QAction(MainWindow)
        self.actionShowAboutMe.setObjectName("actionShowAboutMe")

        self.menuexcel.addAction(self.action_sheet)
        self.menuexcel.addAction(self.action)
        self.menu.addAction(self.actiongong)
        self.menu.addAction(self.menuexcel.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        # 重点
        self.menu_2.addAction(self.actionShowAboutMe)
        self.actionShowAboutMe.triggered.connect(self.showaboutme)

        self.actiongong.triggered.connect(self.showeditNames)
        self.action_sheet.triggered.connect(self.showmergeSheets)
        self.action.triggered.connect(self.showextractExcel)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "元宝的工具箱"))
        self.label.setText(_translate("MainWindow", "欢迎使用元宝的工具箱"))
        self.menu.setTitle(_translate("MainWindow", "功能菜单"))
        self.menuexcel.setTitle(_translate("MainWindow", "excel相关"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.actiongong.setText(_translate("MainWindow", "批量修改名称"))
        self.action_sheet.setText(_translate("MainWindow", "合并sheet内容"))
        self.action.setText(_translate("MainWindow", "提取内容"))
        self.actionShowAboutMe.setText(_translate("MainWindow", "关于我"))

    def showaboutme(self):
        self.child_aboutMe = aboutMe.Ui_Dialog()
        self.child_aboutMe.show()

    def showeditNames(self):
        self.child_editNames = editNames.Ui_Dialog()
        self.child_editNames.show()

    def showmergeSheets(self):
        self.child_mergeSheets = mergeSheets.Ui_Dialog()
        self.child_mergeSheets.show()

    def showextractExcel(self):
        self.child_extractExcel = extractExcel.Ui_Dialog()
        self.child_extractExcel.show()
