# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mergeSheets.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(507, 315)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 521, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(0, 20, 371, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(0, 150, 231, 31))
        self.pushButton.setObjectName("pushButton")

        # 点击合成所有sheets
        self.pushButton.clicked.connect(self.mergeallsheets)

        self.toolButton = QtWidgets.QToolButton(self.tab)
        self.toolButton.setGeometry(QtCore.QRect(370, 20, 41, 31))
        self.toolButton.setObjectName("toolButton")

        # 获取现存excel路径1
        self.toolButton.clicked.connect(self.getexcelpath1)

        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 381, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 451, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_5.setGeometry(QtCore.QRect(0, 120, 371, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_6.setGeometry(QtCore.QRect(0, 70, 371, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(0, 50, 451, 20))
        self.label_12.setObjectName("label_12")
        self.toolButton_6 = QtWidgets.QToolButton(self.tab)
        self.toolButton_6.setGeometry(QtCore.QRect(370, 70, 41, 31))
        self.toolButton_6.setObjectName("toolButton_6")

        # 获取新excel的路径1
        self.toolButton_6.clicked.connect(self.getnewpathexcel1)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_2.setGeometry(QtCore.QRect(370, 20, 41, 31))
        self.toolButton_2.setObjectName("toolButton_2")

        self.toolButton_2.clicked.connect(self.getexcelpath2)

        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 20, 371, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setGeometry(QtCore.QRect(40, 80, 42, 22))
        self.spinBox.setObjectName("spinBox")

        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_2.setGeometry(QtCore.QRect(130, 80, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 200, 211, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        # 合并连续sheets
        self.pushButton_2.clicked.connect(self.mergetspecifiedsheets)

        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 481, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 50, 491, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(0, 80, 31, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(90, 80, 31, 21))
        self.label_6.setObjectName("label_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_7.setGeometry(QtCore.QRect(0, 120, 371, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(0, 150, 461, 20))
        self.label_8.setObjectName("label_8")
        self.toolButton_7 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_7.setGeometry(QtCore.QRect(370, 120, 41, 31))
        self.toolButton_7.setObjectName("toolButton_7")

        self.toolButton_7.clicked.connect(self.getnewpathexcel2)

        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_8.setGeometry(QtCore.QRect(0, 170, 371, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(0, 100, 471, 20))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 20, 371, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 481, 20))
        self.label_9.setObjectName("label_9")
        self.toolButton_3 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_3.setGeometry(QtCore.QRect(370, 20, 41, 31))
        self.toolButton_3.setObjectName("toolButton_3")

        self.toolButton_3.clicked.connect(self.getexcelpath3)

        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(0, 50, 481, 20))
        self.label_11.setObjectName("label_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 200, 221, 31))
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.mergetspecifiednamessheets)

        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_4.setGeometry(QtCore.QRect(0, 70, 371, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.toolButton_4 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_4.setGeometry(QtCore.QRect(370, 70, 41, 31))
        self.toolButton_4.setObjectName("toolButton_4")

        self.toolButton_4.clicked.connect(self.readnames)

        self.toolButton_8 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_8.setGeometry(QtCore.QRect(370, 120, 41, 31))
        self.toolButton_8.setObjectName("toolButton_8")

        self.toolButton_8.clicked.connect(self.getnewpathexcel3)

        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(0, 150, 461, 20))
        self.label_14.setObjectName("label_14")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_9.setGeometry(QtCore.QRect(0, 120, 371, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_10.setGeometry(QtCore.QRect(0, 170, 371, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(0, 100, 471, 20))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "合并sheets"))
        self.tabWidget.setToolTip(_translate("Dialog", "<html><head/><body><p></p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("Dialog", "<html><head/><body><p></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "点击合并excel所有sheets"))
        self.toolButton.setText(_translate("Dialog", "选择"))
        self.label.setText(_translate("Dialog", "第一步：选择excel所在位置"))
        self.label_2.setText(_translate("Dialog", "第三步：填写新生成excel名字(格式为'aaa')并点击生成"))
        self.label_12.setText(_translate("Dialog", "第二步：选择新生成excel所在位置"))
        self.toolButton_6.setText(_translate("Dialog", "选择"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "合并所有sheets"))
        self.toolButton_2.setText(_translate("Dialog", "选择"))
        self.pushButton_2.setText(_translate("Dialog", "点击合并excel中指定sheets"))
        self.label_3.setText(_translate("Dialog", "第一步：选择excel所在位置"))
        self.label_4.setText(_translate("Dialog", "第二步：选择sheet开始位置与结束位置(0代表第一个)"))
        self.label_5.setText(_translate("Dialog", "开始："))
        self.label_6.setText(_translate("Dialog", "结束："))
        self.label_8.setText(_translate("Dialog", "第三步：填写新生成excel名字(格式为aaa.xlsx)并点击生成"))
        self.toolButton_7.setText(_translate("Dialog", "选择"))
        self.label_13.setText(_translate("Dialog", "第三步：选择新生成excel所在位置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "合并连续sheets"))
        self.label_9.setText(_translate("Dialog", "第一步：选择excel所在位置"))
        self.toolButton_3.setText(_translate("Dialog", "选择"))
        self.label_11.setText(_translate("Dialog", "第二步：填写sheet表具体名称（用数字\",\"隔开），填写完成后点击确定"))
        self.pushButton_3.setText(_translate("Dialog", "点击合并excel中具体名称sheets"))
        self.toolButton_4.setText(_translate("Dialog", "确定"))
        self.toolButton_8.setText(_translate("Dialog", "选择"))
        self.label_14.setText(_translate("Dialog", "第四步：填写新生成excel名字(格式为aaa.xlsx)并点击生成"))
        self.label_15.setText(_translate("Dialog", "第三步：选择新生成excel所在位置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "合并具体名称sheets"))

    # 合并所有sheets
    def getexcelpath1(self):
        self.pathexcel1, filetype = QtWidgets.QFileDialog.getOpenFileName(self, "选取文件", "C:/", "xlsx Files (*.xlsx)")
        self.textEdit.setText(self.pathexcel1)

    def getnewpathexcel1(self):
        self.newpathexcel1 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取文件", "C:/")
        self.textEdit_6.setText(self.newpathexcel1)

    def mergeallsheets(self):
        newnameexcel1 = self.textEdit_5.toPlainText()
        dfs = pd.read_excel(f"{self.pathexcel1}", sheet_name=None, engine="openpyxl")
        pd.concat(dfs).to_excel(f"{self.newpathexcel1}/{newnameexcel1}.xlsx")

    # 合并连续sheets
    def getexcelpath2(self):
        self.pathexcel2, filetype = QtWidgets.QFileDialog.getOpenFileName(self, "选取文件", "C:/", "xlsx Files (*.xlsx)")
        self.textEdit_2.setText(self.pathexcel2)

    def getnewpathexcel2(self):
        self.newpathexcel2 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取文件", "C:/")
        self.textEdit_7.setText(self.newpathexcel2)

    def mergetspecifiedsheets(self):
        newnameexcel2 = self.textEdit_8.toPlainText()
        dfs = [pd.read_excel(f"{self.pathexcel2}", sheet_name=index, engine="openpyxl") for index in
               range(self.spinBox.value(), self.spinBox_2.value())]
        pd.concat(dfs).to_excel(f"{self.newpathexcel2}/{newnameexcel2}.xlsx")

    # 合并具体名称sheets
    def getexcelpath3(self):
        self.pathexcel3, filetype = QtWidgets.QFileDialog.getOpenFileName(self, "选取文件", "C:/", "xlsx Files (*.xlsx)")
        self.textEdit_3.setText(self.pathexcel3)

    def readnames(self):
        namesheets = self.textEdit_4.toPlainText()
        self.arrnamessheets = namesheets.split(',')

    def getnewpathexcel3(self):
        self.newpathexcel3 = QtWidgets.QFileDialog.getExistingDirectory(self, "选取文件", "C:/")
        self.textEdit_9.setText(self.newpathexcel3)

    def mergetspecifiednamessheets(self):
        newnameexcel3 = self.textEdit_10.toPlainText()
        dfs = [pd.read_excel(f"{self.pathexcel3}", sheet_name=name, engine="openpyxl") for name in self.arrnamessheets]
        pd.concat(dfs).to_excel(f"{self.newpathexcel3}/{newnameexcel3}.xlsx")
